### ISSUE TITLE
add containers?

### ISSUE THREAD

**Issue by c-cube** [rleonid/bitset_shootout#1]
If you're interested, you can add https://github.com/c-cube/ocaml-containers/blob/master/src/data/CCBV.mli to it. I'm not sure it will perform very well, but it's interesting nevertheless.

**Comment by rleonid** [comment]
Thank you! I'll try, this is still a WIP.

**Comment by rleonid** [comment]
Added, and the results look great! Thank you for creating such a good solution. I'll extend the "shootout" with other tests, but in the meantime I'll definitely use containers.

**Comment by c-cube** [comment]
There are a few caveats regarding CCBV though (wrt length mostly). I've been using the basics for a while and they're solid, but it would not hurt to contribute a few tests to containers if you have time to do so! :)
